Repository winnow-2023/best-choice-fe, pull requests merged in 2023-09, with the labels that each got.

#78 useFetchData hook 수정, 데이터 불러오기 테스트
  src/components/comment/Comment.tsx
  src/components/comment/CommentList.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/MainChattingList.tsx
  src/components/contents/PostCardList.tsx
  src/components/modal/UploadPost.tsx
  src/hooks/useFetchData.tsx
  src/states/recoil.ts
  src/views/HotListPage.tsx
  src/views/MainPage.tsx
  src/views/PostDetailPage.tsx
  src/views/PostListPage.tsx
Labels: Refactor

#79 소셜로그인 구현 및 recoil/세션스토리지에 토큰 저장, 토큰 넣어서 회원 데이터 요청 구현, 로그인 상태에 따라 헤더 버튼 변경 구현
  package-lock.json
  package.json
  src/components/common/Header.tsx
  src/components/contents/NotificationCard.tsx
  src/components/contents/PostCardList.tsx
  src/components/modal/EnterChatRoom.tsx
  src/hooks/useFetchData.tsx
  src/main.tsx
  src/router/router.tsx
  src/states/recoil.ts
  src/views/HotListPage.tsx
  src/views/LoginCallbackPage.tsx
  src/views/LoginPage.tsx
  src/views/MainPage.tsx
  src/views/MemberPage.tsx
  src/views/PostListPage.tsx
Labels: enhancement, Refactor

#80 로그인 시 유저 정보 recoil 전역 상태로 저장, 전체 Suspense 처리, useFetchData response 데이터 return 형식 수정, 투표글 상세페이지 데이터 연동
  src/App.tsx
  src/components/comment/CommentList.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/MainChattingList.tsx
  src/components/contents/NotificationCard.tsx
  src/components/contents/PostCardList.tsx
  src/components/contents/PostDetail.tsx
  src/hooks/useFetchData.tsx
  src/states/recoil.ts
  src/states/recoilType.ts
  src/views/LoginCallbackPage.tsx
  src/views/MainPage.tsx
  src/views/MemberPage.tsx
  src/views/NotificationPage.tsx
  src/views/PostDetailPage.tsx
  src/views/SearchPage.tsx
Labels: enhancement, Refactor

#82 투표 작성 post 테스트 완료, 검색 기능 구현 완료, moment.js 라이브러리로 날짜 변환, api url 수정, 에디터 toolbar 수정
  package-lock.json
  package.json
  src/components/comment/Comment.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/contents/PostCard.tsx
  src/components/contents/PostCardList.tsx
  src/components/contents/PostDetail.tsx
  src/components/contents/Search.tsx
  src/components/create/TextEditor.tsx
  src/components/modal/UploadPost.tsx
  src/main.tsx
  src/views/PostDetailPage.tsx
  src/views/PostListPage.tsx
Labels: enhancement, Refactor

#84 투표글 등록/닉네임/그래프 오류 해결, 투표글 상세페이지 투표/추천/삭제 기능 구현, 닉네임 변경 기능 구현, 리스트페이지 limit 수정
  package-lock.json
  package.json
  src/components/comment/CommentList.tsx
  src/components/common/LikeBtn.tsx
  src/components/common/button/CommentLikeBtn.tsx
  src/components/common/button/PostLikeBtn.tsx
  src/components/contents/PostCardList.tsx
  src/components/contents/PostDetail.tsx
  src/components/contents/VoteGraph.tsx
  src/components/modal/BasicModal.tsx
  src/components/modal/CancelCreate.tsx
  src/components/modal/ChangeNickname.tsx
  src/components/modal/EnterChatRoom.tsx
  src/components/modal/UploadPost.tsx
  src/components/skeletonUI/LoadNotification.tsx
  src/states/recoil.ts
  src/states/recoilType.ts
  src/views/HotListPage.tsx
  src/views/LoginCallbackPage.tsx
  src/views/MemberPage.tsx
  src/views/PostListPage.tsx
Labels: bug, enhancement, Refactor

#86 댓글 페이지네이션 구현, 댓글 줄바꿈 적용, 댓글 컴포넌트 일부 수정
  package-lock.json
  package.json
  src/assets/style.css
  src/components/comment/Comment.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
Labels: enhancement, Refactor

#87 비로그인 투표/추천/신고 버튼 클릭시 모달 처리, 투표글 신고 기능 구현, 채팅방 입장/개설 버튼 조건부 렌더링, 댓글 추천/추천 취소 및 기록 반영
  package-lock.json
  package.json
  src/assets/style.css
  src/components/comment/CommentList.tsx
  src/components/common/button/CommentLikeBtn.tsx
  src/components/common/button/EnterChatRoomBtn.tsx
  src/components/common/button/MakeChatRoomBtn.tsx
  src/components/common/button/PostLikeBtn.tsx
  src/components/common/button/ScrollTopBtn.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/MainChattingList.tsx
  src/components/contents/NotificationCard.tsx
  src/components/contents/PostDetail.tsx
  src/components/create/CreatePost.tsx
  src/components/create/FileInput.tsx
  src/components/create/TagInput.tsx
  src/mocks/mockType.ts
  src/views/ChatListPage.tsx
  src/views/HotListPage.tsx
  src/views/MainPage.tsx
  src/views/MemberPage.tsx
  src/views/NotificationPage.tsx
  src/views/PostDetailPage.tsx
  src/views/PostListPage.tsx
  src/views/SearchPage.tsx
Labels: enhancement, Refactor

#88 채팅방 컴포넌트 생성 및 기본 세팅, 게시글 작성 페이지 코드 수정, 상세 페이지 날짜 형식에 시간 추가
  src/assets/style.css
  src/components/chat/Chat.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/Header.tsx
  src/components/chat/InfoBar.tsx
  src/components/chat/MessageForm.tsx
  src/components/contents/PostDetail.tsx
  src/components/create/CreatePost.tsx
  src/components/create/FileInput.tsx
  src/components/create/TagInput.tsx
  src/components/create/TextEditor.tsx
  src/components/modal/UploadPost.tsx
  src/router/router.tsx
  src/states/recoil.ts
  src/states/recoilType.ts
  vite.config.ts
Labels: enhancement, Refactor

#93 상세페이지 채팅방 개설/입장 버튼 수정
  src/components/contents/PostDetail.tsx
Labels: Refactor

#94 댓글 페이지네이션 스타일 수정, 검색 페이지 추천 해시태그 기능 추가(임시), 이미지/동영상 분리 업로드, 파일 업로드 용량 제한 안내 추가
  src/assets/style.css
  src/components/comment/Comment.tsx
  src/components/comment/CommentList.tsx
  src/components/contents/Search.tsx
  src/components/create/CreatePost.tsx
  src/components/create/FileInput.tsx
  src/components/modal/UploadPost.tsx
  src/states/recoil.ts
  src/states/recoilType.ts
Labels: enhancement, Refactor

#95 로그아웃 시 헤더 로그인 버튼으로 변경되도록 수정, 상세페이지 이미지/동영상 데이터 렌더링 및 반응형 구현, 채팅방 나가기 버튼 로직 작성
  src/components/chat/ChatHeader.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/Header.tsx
  src/components/contents/PostDetail.tsx
  src/views/MemberPage.tsx
Labels: enhancement, Refactor

#97 댓글 좋아요 비회원 처리 코드 수정, 해시태그 UI 변경 및 onChange 함수 분리, searchTagClick 함수 useCallback으로 감싸기, content state default 값 변경
  src/components/common/button/CommentLikeBtn.tsx
  src/components/contents/Search.tsx
  src/components/create/CreatePost.tsx
  src/components/create/FileInput.tsx
  src/components/create/TagInput.tsx
  src/states/recoil.ts
  src/states/recoilType.ts
Labels: Refactor

#98 채팅방 소켓 연결 오류 해결, 채팅 메시지에 닉네임+시간 추가, 채팅방 페이지에서 헤더+푸터 제거 및 채팅방 디자인 수정
  src/App.tsx
  src/components/chat/ChatHeader.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/InfoBar.tsx
  src/router/router.tsx
Labels: enhancement, Refactor

#99 닉네임 유효성 검사 추가
  src/components/modal/ChangeNickname.tsx
Labels: enhancement

#100 본인이 보낸 채팅일 경우 말풍선 방향 오른쪽으로 수정, 새로운 채팅 오면 스크롤 바닥으로 이동하도록 구현, 채팅 인원 수 배지 스타일 분기 처리
  src/components/chat/ChatHeader.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/InfoBar.tsx
  src/components/chat/MessageForm.tsx
  src/components/common/ChatUserBadge.tsx
  src/components/contents/ChatCardList.tsx
Labels: Refactor

#103 채팅 리스트 조회, 채팅방 입장 버튼 수정, 채팅방 종료 기능 추가, 채팅 리스트 시간 추가 및 UI 변경
  src/components/chat/ChatHeader.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/InfoBar.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/MainChattingList.tsx
  src/components/modal/EnterChatRoom.tsx
  src/mocks/mockType.ts
Labels: Refactor

#104 UseInfiniteQuery사용 무한스크롤 구현, 채팅방 입장 버튼 디자인 조건부 렌더링
  package-lock.json
  src/components/common/button/EnterChatRoomBtn.tsx
  src/components/contents/PostCardList.tsx
  src/components/contents/PostDetail.tsx
  src/components/modal/EnterChatRoom.tsx
  src/hooks/useInfinitePosts.tsx
  src/views/PostListPage.tsx
Labels: enhancement, Refactor

#106 채팅방 입장 제한 기능 추가, 파일 업로드 코드 일부 수정
  src/components/common/button/EnterChatRoomBtn.tsx
  src/components/contents/PostDetail.tsx
  src/components/create/FileInput.tsx
  src/components/modal/EnterChatRoom.tsx
Labels: Refactor

#108 로그인/로그아웃 시 alret/confirm 창 모달로 변경, 로그아웃 후 본인 글에 삭제 버튼 뜨는 오류 수정
  src/assets/style.css
  src/components/chat/ChatList.tsx
  src/components/contents/PostDetail.tsx
  src/views/LoginCallbackPage.tsx
  src/views/MemberPage.tsx
Labels: Refactor

#109 모달창 닫았을 때 스크롤 안 생기는 오류 수정, 채팅 말풍선/시간 위치 조건문 긍정문으로 수정, 변수명 수정 및 코드 리팩토링 리팩토링
  public/logoName.png
  src/components/chat/ChatList.tsx
  src/components/common/button/EnterChatRoomBtn.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/PostCard.tsx
  src/components/contents/PostDetail.tsx
  src/components/modal/CancelCreate.tsx
  src/mocks/mockType.ts
  src/router/router.tsx
  src/views/LoginPage.tsx
  src/views/MemberPage.tsx
Labels: Refactor

#111 무한스크롤 데이터 없는 경우에 대한 조건문 코드 수정, 한 페이지당 데이터 개수 변수로 분리, 채팅방 리스트 카드 날짜 형식 수정
  src/components/contents/ChatCardList.tsx
  src/components/contents/PostCardList.tsx
  src/hooks/useInfinitePosts.tsx
Labels: bug, Refactor

#112 댓글 입력 컴포넌트에 닉네임 추가, 옵션 선택 배지 스타일 수정, 해시태그 검색 결과 텍스트 코드 수정
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/contents/Search.tsx
Labels: Refactor
