Repository winnow-2023/best-choice-fe, pull requests merged in 2023-08, with the labels that each got.

#45 채팅방 입장 모달창이 데이터 받아서 보여주는 방식 리팩토링
  src/components/MainChattingList.tsx
  src/components/contents/ChatCardList.tsx
  src/components/modal/EnterChatRoom.tsx
Labels: Refactor

#46 투표 작성글 수정 및 기능 추가
  src/assets/style.css
  src/components/common/FileInput.tsx
  src/components/common/TagInput.tsx
  src/components/common/TextEditor.tsx
  src/components/contents/CreatePost.tsx
Labels: enhancement, Refactor

#49 알림 mock 데이터 생성, 알림메시지 모달창 팝업 구현 및 파일명 수정, 메인 채팅 컴포넌트 파일 위치 이동
  src/components/NotificationCard.tsx
  src/components/NotificationMessage.tsx
  src/components/contents/MainChattingList.tsx
  src/mocks/handler.ts
  src/mocks/mockDatas/notificationData.ts
  src/mocks/mockType.ts
  src/views/MainPage.tsx
  src/views/NotificationPage.tsx
Labels: enhancement, Refactor

#50 투표글 작성 컴포넌트 모달 추가
  src/components/contents/CreatePost.tsx
  src/components/modal/CancelCreate.tsx
  src/components/modal/UploadPost.tsx
Labels: enhancement

#54 채팅방 입장 모달 조회 데이터 수정, 투표글 상세페이지 구현
  package-lock.json
  package.json
  src/components/common/LikeBtn.tsx
  src/components/contents/PostDetail.tsx
  src/components/contents/VoteGraph.tsx
  src/components/modal/EnterChatRoom.tsx
  src/mocks/mockDatas/activeChatListData.ts
  src/mocks/mockDatas/postListData.ts
  src/mocks/mockType.ts
  src/views/PostDetailPage.tsx
Labels: bug, enhancement, Refactor

#53 해시태그 삭제 에러 해결
  src/components/common/TagInput.tsx
Labels: bug

#55 댓글 삭제, 게시글 신고 모달
  src/components/common/CommentList.tsx
  src/components/contents/PostDetail.tsx
  src/components/modal/BasicModal.tsx
Labels: enhancement

#56 추천 버튼 및 투표하기 버튼 기능 구현, 디자인 수정, filter 오류 해결
  src/assets/style.css
  src/components/common/LikeBtn.tsx
  src/components/common/TagInput.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/Comment.tsx
  src/components/contents/PostCard.tsx
  src/components/contents/PostDetail.tsx
  src/components/modal/EnterChatRoom.tsx
  src/views/HotListPage.tsx
  src/views/MemberPage.tsx
  src/views/PostListPage.tsx
Labels: bug, enhancement

#57 로그인 페이지 레이아웃 구현, 추천 버튼 컴포넌트 수정 및 댓글에 적용, 모달 디자인 수정
  src/components/common/CommentInput.tsx
  src/components/common/CommentList.tsx
  src/components/common/LikeBtn.tsx
  src/components/contents/Comment.tsx
  src/components/contents/PostDetail.tsx
  src/components/modal/BasicModal.tsx
  src/components/modal/CancelCreate.tsx
  src/components/modal/ChangeNickname.tsx
  src/components/modal/EnterChatRoom.tsx
  src/components/modal/UploadPost.tsx
  src/views/LoginPage.tsx
Labels: enhancement, Refactor

#58 에러 페이지 구현 및 ErrorBoundary 코드 작성
  package-lock.json
  package.json
  src/App.tsx
  src/views/ErrorPage.tsx
Labels: enhancement

#59 ErrorBoundary 코드 위치 main태그 안으로 수정, 시맨틱 태그로 수정
  src/App.tsx
  src/views/ChatListPage.tsx
  src/views/MainPage.tsx
Labels: Refactor

#61 없는 페이지 경로로 이동했을 때 404 페이지 구현
  src/router/router.tsx
  src/views/ErrorPage.tsx
Labels: enhancement, Refactor

#66 검색 컴포넌트 및 투표 작성 컴포넌트 수정, 해시태그 중복 입력 에러 해결
  src/components/common/CommentInput.tsx
  src/components/common/FileInput.tsx
  src/components/common/TagInput.tsx
  src/components/contents/Comment.tsx
  src/components/contents/CreatePost.tsx
  src/components/contents/Search.tsx
  src/components/modal/UploadPost.tsx
  src/views/MemberPage.tsx
  src/views/PostDetailPage.tsx
  src/views/PostListPage.tsx
  src/views/SearchPage.tsx
Labels: bug, Refactor

#67 투표글 카드, 알림 메시지 컴포넌트 스켈레톤UI 제작 및 Suspense로 적용
  src/components/NotificationCard.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/MainChattingList.tsx
  src/components/contents/PostCardList.tsx
  src/components/skeletonUI/LoadMainChat.tsx
  src/components/skeletonUI/LoadNotification.tsx
  src/components/skeletonUI/LoadPostCard.tsx
  src/views/ChatListPage.tsx
  src/views/HotListPage.tsx
  src/views/MainPage.tsx
  src/views/MemberPage.tsx
  src/views/NotFoundPage.tsx
  src/views/NotificationPage.tsx
  src/views/PostListPage.tsx
Labels: enhancement

#68 prettier 추가 및 컴포넌트 폴더 구조 수정
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  src/components/comment/Comment.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/contents/MainChattingList.tsx
  src/components/contents/NotificationCard.tsx
  src/components/contents/PostDetail.tsx
  src/components/create/CreatePost.tsx
  src/components/create/FileInput.tsx
  src/components/create/TagInput.tsx
  src/components/create/TextEditor.tsx
  src/components/skeletonUI/LoadMainChat.tsx
  src/views/CreatePostPage.tsx
  src/views/NotificationPage.tsx
  src/views/PostDetailPage.tsx
Labels: Refactor

#69 투표글 상세페이지 스켈레톤UI 제작 및 Suspense 적용
  .prettierrc
  src/components/contents/PostDetail.tsx
  src/components/contents/Search.tsx
  src/components/create/CreatePost.tsx
  src/components/skeletonUI/LoadMainChat.tsx
  src/components/skeletonUI/LoadNotification.tsx
  src/components/skeletonUI/LoadPostCard.tsx
  src/components/skeletonUI/LoadPostDetail.tsx
  src/views/ChatListPage.tsx
  src/views/CreatePostPage.tsx
  src/views/MemberPage.tsx
  src/views/PostDetailPage.tsx
  src/views/SearchPage.tsx
Labels: enhancement, Refactor

#70 컴포넌트별 에러 처리
  src/components/comment/Comment.tsx
  src/components/common/ErrorMessage.tsx
  src/components/contents/ChatCardList.tsx
  src/components/contents/MainChattingList.tsx
  src/components/contents/NotificationCard.tsx
  src/components/contents/PostCardList.tsx
  src/views/ChatListPage.tsx
  src/views/HotListPage.tsx
  src/views/MainPage.tsx
  src/views/MemberPage.tsx
  src/views/NotificationPage.tsx
  src/views/PostDetailPage.tsx
  src/views/PostListPage.tsx
Labels: Refactor

#72 해시태그 컴포넌트 입력 제한 설정, 파일 업로드 에러 해결, 투표 항목 컴포넌트로 분리, 투표 작성 페이지 일부 수정
  src/components/comment/CommentList.tsx
  src/components/create/CreatePost.tsx
  src/components/create/FileInput.tsx
  src/components/create/OptionInput.tsx
  src/components/create/TagInput.tsx
  src/components/modal/CancelCreate.tsx
Labels: bug, Refactor

#74 CSS / UI 디자인 수정, 투표 작성 페이지 작성 완료 버튼 모달 매개변수 이름 변경, 해시태그 컴포넌트 유효성 검사 수정
  src/assets/style.css
  src/components/comment/Comment.tsx
  src/components/common/ErrorMessage.tsx
  src/components/create/CreatePost.tsx
  src/components/create/FileInput.tsx
  src/components/create/TagInput.tsx
Labels: Refactor

#76 로컬/배포 환경에서 백엔드 서버 연동 후 데이터 요청, proxy 설정
  src/components/contents/PostCardList.tsx
  vercel.json
  vite.config.ts
Labels: enhancement
